# Generated by Django 4.1.7 on 2023-04-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thatre',
            fields=[
                ('t_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_release_data', models.DateField()),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.thatre')),
            ],
        ),
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('heroine', models.CharField(max_length=100)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.movies')),
            ],
        ),
    ]
