# Generated by Django 4.1.7 on 2023-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thatre',
            name='email',
            field=models.EmailField(default='madhu@gmail.com', max_length=254),
        ),
    ]
